# Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import folium
import folium.plugins as plugins
from ipyleaflet.velocity import Velocity
import ipyleaflet
from ipywidgets import Layout

# Data Importing and Preperation

In [2]:
data = pd.read_csv('../data/sorted_data_large.csv')
data.sample(5)

,Unnamed: 0,LAT,LON,YEAR,DOY,EVLAND,GWETPROF,GWETROOT,GWETTOP,PRECSNO,...,TS_MIN,WD2M,WD50M,WS2M,WS2M_MAX,WS2M_MIN,WS50M,WS50M_MAX,WS50M_MIN,Z0M
335635,40354,23.0,26.250,2022,121,0.00,0.27,0.27,0.05,0.0,...,19.34,64.5,66.1,3.76,5.11,2.25,7.04,8.96,5.51,0.02
5480,6649,30.0,30.625,2019,20,0.04,0.34,0.34,0.28,0.0,...,3.97,58.9,65.5,1.27,2.35,0.20,3.52,6.17,0.39,0.04
76500,93134,23.5,33.750,2019,278,0.00,0.33,0.33,0.06,0.0,...,24.87,113.3,89.0,2.27,3.69,1.24,4.47,6.89,2.12,0.01
279293,94366,30.5,33.750,2021,281,0.01,0.33,0.33,0.11,0.0,...,16.08,359.0,358.9,3.22,5.08,1.30,5.64,7.79,4.39,0.01
315218,15497,23.0,30.625,2022,47,0.00,0.27,0.27,0.08,0.0,...,6.19,359.2,357.3,3.92,5.57,2.08,7.71,9.88,5.72,0.01

In [3]:
df = data[['LAT', 'LON', 'YEAR', 'DOY', 'WD2M', 'WD50M', 'WS2M', 'WS2M_MAX', 'WS2M_MIN', 'WS50M', 'WS50M_MAX', 'WS50M_MIN']]
df.sample(5)

,LAT,LON,YEAR,DOY,WD2M,WD50M,WS2M,WS2M_MAX,WS2M_MIN,WS50M,WS50M_MAX,WS50M_MIN
125910,24.0,27.500,2020,92,357.0,0.3,3.17,4.94,1.56,6.29,8.01,4.07
193873,26.0,30.000,2020,338,264.1,275.6,1.05,2.38,0.22,1.92,3.56,0.28
206363,28.5,31.250,2021,17,256.2,259.9,3.17,6.25,1.17,6.65,9.61,3.40
283686,30.0,29.375,2021,297,0.2,2.6,2.97,5.42,1.12,5.55,7.91,3.53
420707,24.5,35.000,2023,64,88.6,96.0,1.62,3.25,0.20,2.81,4.52,0.41

# Data Analysis with pandas

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503976 entries, 0 to 503975
Data columns (total 12 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   LAT        503976 non-null  float64
 1   LON        503976 non-null  float64
 2   YEAR       503976 non-null  int64
 3   DOY        503976 non-null  int64
 4   WD2M       503976 non-null  float64
 5   WD50M      503976 non-null  float64
 6   WS2M       503976 non-null  float64
 7   WS2M_MAX   503976 non-null  float64
 8   WS2M_MIN   503976 non-null  float64
 9   WS50M      503976 non-null  float64
 10  WS50M_MAX  503976 non-null  float64
 11  WS50M_MIN  503976 non-null  float64
dtypes: float64(10), int64(2)
memory usage: 46.1 MB

In [5]:
df.describe()

,LAT,LON,YEAR,DOY,WD2M,WD50M,WS2M,WS2M_MAX,WS2M_MIN,WS50M,WS50M_MAX,WS50M_MIN
count,503976.000000,503976.000000,503976.000000,503976.000000,503976.000000,503976.000000,503976.000000,503976.000000,503976.000000,503976.000000,503976.000000,503976.000000
mean,26.692029,29.938859,2020.999452,183.100219,217.817401,210.996520,3.198564,4.991968,1.632560,6.138681,8.472295,3.706217
std,2.694820,2.821385,1.414021,105.424248,141.721805,144.831581,1.085977,1.403819,0.871049,1.706020,1.770092,1.997519
min,22.500000,25.000000,2019.000000,1.000000,0.000000,0.000000,0.490000,0.860000,0.000000,0.760000,1.370000,0.000000
25%,24.500000,27.500000,2020.000000,92.000000,40.800000,33.700000,2.400000,4.030000,1.070000,4.960000,7.400000,2.130000
50%,26.500000,30.000000,2021.000000,183.000000,302.500000,298.000000,3.120000,4.960000,1.490000,6.140000,8.540000,3.690000
75%,29.000000,32.500000,2022.000000,274.000000,339.700000,340.100000,3.890000,5.880000,2.080000,7.310000,9.560000,5.150000
max,31.500000,36.250000,2023.000000,366.000000,360.000000,360.000000,10.600000,15.480000,9.090000,16.570000,23.520000,13.270000

# Analysis with ipyleaflet

In [24]:
# Define map boundaries
min_lon, max_lon = 24.5, 37
min_lat, max_lat = 22, 32

# Create Map
m = ipyleaflet.Map(
    center=[(min_lat + max_lat) / 2, (min_lon + max_lon) / 2],  # Centered within bounds
    zoom=6,
    layout=Layout(width="600px", height="600px"),  # Set fixed size
    basemap=ipyleaflet.basemaps.OpenStreetMap.Mapnik,
    max_bounds=[[min_lat, min_lon], [max_lat, max_lon]],  # Restrict panning
    max_bounds_visible=True  # Prevents moving outside max/min bounds
)

# Ensure df is a full copy to avoid warnings
df = df.copy()
df.loc[:, "ZWC2M"] = df["WS2M"] * np.cos(df["WD2M"])
df.loc[:, "MWC2M"] = df["WS2M"] * np.sin(df["WD2M"])

# Initialize global wind variable
wind = None  

# Function to update wind velocity layer
def update_wind(change):
    global wind  
    year = year_slider.value
    doy = day_slider.value  
    
    # Extract data for selected year & day
    wind_data = df[(df["YEAR"] == year) & (df["DOY"] == doy)].copy()  
    
    if wind_data.empty:
        return  
    
    wind_layer = Velocity(
        data=wind_data[["LAT", "LON", "ZWC2M", "MWC2M"]].set_index(["LAT", "LON"]).to_xarray(),
        zonal_speed="ZWC2M",
        meridional_speed="MWC2M",
        latitude_dimension="LAT",
        longitude_dimension="LON",
        velocity_scale=0.05,
        max_velocity=10
    )
    
    if wind is not None:
        m.remove(wind)
    m.add(wind_layer)
    
    wind = wind_layer  

# Create Year Slider (2019â€“2023)
year_slider = widgets.IntSlider(
    value=2019, min=2019, max=2023, step=1, description="Year"
)
year_slider.observe(update_wind, names="value")

# Create Day Slider (DOY: 1â€“365)
day_slider = widgets.IntSlider(
    value=1, min=1, max=365, step=1, description="Day"
)
day_slider.observe(update_wind, names="value")

# Display map and sliders
ui = widgets.VBox([year_slider, day_slider])
display(m, ui)

# Initialize the first wind layer
update_wind({"new": 1})

Map(center=[27.0, 30.75], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_ouâ€¦

VBox(children=(IntSlider(value=2019, description='Year', max=2023, min=2019), IntSlider(value=1, description='â€¦

In [21]:
# Define map boundaries
min_lon, max_lon = 24.5, 37
min_lat, max_lat = 22, 32

# Create Map
m = ipyleaflet.Map(
    center=[(min_lat + max_lat) / 2, (min_lon + max_lon) / 2],  # Centered within bounds
    zoom=6,
    layout=Layout(width="600px", height="600px"),  # Set fixed size
    basemap=ipyleaflet.basemaps.OpenStreetMap.Mapnik,
    max_bounds=[[min_lat, min_lon], [max_lat, max_lon]],  # Restrict panning
    max_bounds_visible=True  # Prevents moving outside max/min bounds
)

# Ensure df is a full copy to avoid warnings
df = df.copy()
df.loc[:, "ZWC50M"] = df["WS50M"] * np.cos(df["WD50M"])
df.loc[:, "MWC50M"] = df["WS50M"] * np.sin(df["WD50M"])

# Initialize global wind variable
wind = None  

# Function to update wind velocity layer
def update_wind(change):
    global wind  
    year = year_slider.value
    doy = day_slider.value  
    
    # Extract data for selected year & day
    wind_data = df[(df["YEAR"] == year) & (df["DOY"] == doy)].copy()  
    
    if wind_data.empty:
        return  
    
    wind_layer = Velocity(
        data=df[['LAT', 'LON', 'ZWC50M', 'MWC50M']][(df['YEAR'] == 2019) & (df['DOY'] == 1)].set_index(['LAT', 'LON']).to_xarray(),
        zonal_speed='ZWC50M',
        meridional_speed='MWC50M',
        latitude_dimension='LAT',
        longitude_dimension='LON',
        velocity_scale=0.05,
        max_velocity=20
    )
    
    if wind is not None:
        m.remove(wind)
    m.add(wind_layer)
    
    wind = wind_layer  

# Create Year Slider (2019â€“2023)
year_slider = widgets.IntSlider(
    value=2019, min=2019, max=2023, step=1, description="Year"
)
year_slider.observe(update_wind, names="value")

# Create Day Slider (DOY: 1â€“365)
day_slider = widgets.IntSlider(
    value=1, min=1, max=365, step=1, description="Day"
)
day_slider.observe(update_wind, names="value")

# Display map and sliders
ui = widgets.VBox([year_slider, day_slider])
display(m, ui)

# Initialize the first wind layer
update_wind({"new": 1})

Map(center=[27.0, 30.75], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_ouâ€¦

VBox(children=(IntSlider(value=2019, description='Year', max=2023, min=2019), IntSlider(value=1, description='â€¦